stages:
  - lint
  - style
  - test
  - build
  - deploy

.frontend:
  image: node:latest
  cache:
    key: frontend
    paths:
      - node_modules/
  before_script:
    - yarn install

.secoder:
  image: registry.secoder.net/tool/deployer
  only:
    - master
    - develop

frontend-lint:
  extends: .frontend
  stage: lint
  script:
    - yarn eslint . --max-warnings 0

frontend-style:
  extends: .frontend
  stage: style
  needs:
    - frontend-lint
  script:
    - yarn prettier --check .

frontend-test:
  extends: .frontend
  stage: test
  needs:
    - frontend-style
  script:
    - yarn test --coverage
  after_script:
    - curl http://10.0.0.11/sonar-scanner.tar.gz -s -o /tmp/sonar-scanner.tar.gz
    - tar -xf /tmp/sonar-scanner.tar.gz -C /opt
    - /opt/sonar-scanner/bin/sonar-scanner

frontend-build:
  extends: .secoder
  stage: build
  needs:
    - frontend-test
  variables:
    BUILD_IMAGE_NAME: $CI_REGISTRY_IMAGE
    BUILD_IMAGE_TAG: $CI_COMMIT_REF_SLUG
    BUILD_IMAGE_USERNAME: $CI_REGISTRY_USER
    BUILD_IMAGE_PASSWORD: $CI_REGISTRY_PASSWORD
  script:
    - deployer build

frontend-deploy:
  extends: .secoder
  stage: deploy
  needs:
    - frontend-build
  script:
    - deployer dyno replace $CI_PROJECT_NAME "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" "$REGISTRY_USER" "$REGISTRY_PWD"
